# The permission default sets who will get the 'ifu.sit' permission by default
# - 'true' : Everyone can use the /sit command
# - 'op' : Only operators (OPs) can use the /sit command
# - 'not_op' : Everyone but operators (OPs) can use the /sit command
# - 'false' : No one can use the /sit command unless the 'simplesit.sit' permission is given 
# to them via a permissions plugin.
sit-permission-default: true

# All messages can be colored with '&' plus colorID. Color IDS: http://minecraft.gamepedia.com/Formatting_codes

# The message sent to the player when they sit down
sitdown-message: '&bYou are now sitting.'

# The message sent when the player gets up from sitting.
situp-message: '&bYou are no longer sitting.'

# The message sent when the player is unable to sit (In air)
sitfail-message: '&cYou cannot sit in the air!'



#OP-protection: Player can only be op'ed if they are in the "allowed-operators" list
op-protection: true
allowed-operators:
  - roighteously
  - iFardedHelp
#If you try to Op someone who isn't in the list
op-message: "&cThat person isn't allowed to be OP!"
#Players who are operators and are not in the list can't connect and will be deop'ed.
unauthorized-operator-kick-message: '&4You are not allowed to be OP!'
first-pad: "              "
#Message if you type a blocked command | Enter none to disable
blocked-command-message: "Unknown command. Type \"/help\" for help."
#Message shown if you type /pl | Enter none to disable | Players with the permission ifu.bypass will see the real plugins
/pl-message: 'Plugins (0):'

groups:
  #if no group is set via ifu.group.<group> this will be applied
  #do not rename the default group!
  #blocked commands will be automatically removed from the tabcompletion
  default:
    commands:
      - ver
      - version
      - about
      - bukkit
      - icanhasbukkit
      - help
      - '?'
      - me
      - minecraft:me
      - minecraft:help
      - bukkit:?
      - bukkit:help
      - plugins
      - pl
      - bukkit:pl
      - bukkit:plugins
      - bukkit:ver
      - bukkit:version
      - bukkit:about
      #The plugin commands
      - ifutilities:ifu
      - ifu
    #If the value is blacklist, the commands are blocked and invisible
    #If the value is whitelist, the commands only executable and visible
    group-mode: blacklist
    #If a player is in two groups, the group with the higher priority number is used
    #The minimum value is 0
    priority: 0
    #here you can add other groups
    #The group mode is taken from the main group, in this case the main group is "default"
    included-groups:
      - Test

  #This group for example will remove and block all commands
  #add permission ifu.group.test to apply this group
  test:
    commands: []
    group-mode: whitelist
    priority: 1
    included-groups: []


#Don't change
version: "1.3"