name: iFUtilities
version: '${project.version}'
main: ifarded.lol.ifu.IFUtilities
api-version: 1.20
commands:
  ifu:
    description: Everything iFarded.
    usage: /ifu <command>
    permission: ifu.cmd
  civilization:
    description: Go to the civilization
    usage: /civilization
    permission: ifu.civilization