name: Maven

on: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install
      - name: Rename
        run: mv target/ifu-*.jar ./ifu.jar
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ifu.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
